"""vendors udyam_no unique

Revision ID: 3ec3dbd46e1b
Revises: 87828e94a0f2
Create Date: 2026-09-03 14:17:41.488187

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ec3dbd46e1b'
down_revision: Union[str, None] = '87828e94a0f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vendors_udyam_no'), ['udyam_no'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vendors_udyam_no'))

    # ### end Alembic commands ###
